### ISSUE TITLE
 Cannot read properties of undefined (reading 'pollUpdates')

### ISSUE THREAD

**Issue by eduin1178** [andresayac/baileys-api#2]
I get this error sporadically, I assume it is related to webhooks, but I don't understand what I am failing.

TypeError: no se pueden leer las propiedades de indefinido (leyendo 'pollUpdates')
     en EventEmitter.<anónimo> (file:///C:/Users/siemp/Escritorio/BAILEYS-API/whatsapp.js:285:24)
     en EventEmitter.emit (nodo:eventos:526:35)
     en EventEmitter.<anónimo> (C:\Users\siemp\Escritorio\BAILEYS-API\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
     en EventEmitter.emit (nodo:eventos:514:28)
     en Object.flush (C:\Users\siemp\Escritorio\BAILEYS-API\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
     en ProcessNodeWithBuffer (C:\Users\siemp\Escritorio\BAILEYS-API\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:685:12)
Ejecutando la limpieza antes de la salida.

# WEBHOOK CONFIGURATION
APP_WEBHOOK_URL="https://webhook.site/8dc62a8d-f53f-4f56-9535-f70c46fd504b"
APP_WEBHOOK_ALLOWED_EVENTS=MESSAGES_UPSERT,MESSAGES_DELETE,MESSAGES_UPDATE
APP_WEBHOOK_FILE_IN_BASE64=false

Thanks in advance for your help

**Comment by MohammadAkabar** [comment]
i've got same issue tho

**Comment by andresayac** [comment]
solved  https://github.com/andresayac/baileys-api/commit/192432e0378cdd0a0064ba62b290cea6948bdf5b

**Comment by andresayac** [comment]
solved https://github.com/andresayac/baileys-api/commit/192432e0378cdd0a0064ba62b290cea6948bdf5b
